version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenleaf-gardening
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    command: sh -c "npm install && npm run dev -- --host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    stdin_open: true
    tty: true
